### ISSUE TITLE
Faker not returning new randomized data

### ISSUE THREAD

**Issue by gbrock** [laracasts/TestDummy#86] opened 2015-03-16 00:16 UTC
The following code throws constraint violations on `email` and `username`, but works when only 1 row is generated:

```php
$factory('App\User', function($faker) {
    $created = $faker->dateTimeBetween('-2 years', 'now');

    return [
        'username' => $faker->userName,
        'friendly_name' => $faker->firstName,
        'email' => $faker->safeEmail,
        'created_at' => $created,
        'last_login' => $faker->dateTimeBetween($created, 'now'),
    ];
});
```

Seems like it isn't generating a new value on each faker call...?

**Comment by iamfreee** [comment] 2015-03-16 16:22
Yep, the problem is the closure.

Use without the closure and it works.

**Comment by h-collector** [comment] 2015-03-16 18:03
In the meantime, you can use release 2.1

**Comment by LasseHaslev** [comment] 2015-03-17 10:48
+1

**Comment by h-collector** [comment] 2015-03-18 09:08
The problem is actually because of changed design: "Get the generator stuff out of the Factory and Builder classes" as added FactoriesLoader::normalizeDefinitions is resolving user defined Closures only once after loading factories and not before building new entity.

**Comment by TheShiftExchange** [comment] 2015-03-23 16:01
+1 - this issue is really annoying.

Is it possible to just call the factory method every time I want to create a user? That way the data is randomised on each call - rather than just once?

i.e. it currently doesnt just affect `$faker` - it also affects basic PHP functions like `rand()`.

**Comment by gbrock** [comment] 2015-03-23 19:39
@h-collector's solution works: load 2.1 in your composer.json:

```
    "laracasts/testdummy": "2.1",
```

**Closed** 2015-03-29 15:15 UTC
Labels: bug

**Comment by hootlex** [comment] 2016-02-05 01:07
The issue with php functions like `rand` persists in 2.3.2
